# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(161414)
$foreground = rgb(FAF3E0)
$color0 = rgb(3D3B3B)
$color1 = rgb(90643A)
$color2 = rgb(946638)
$color3 = rgb(947652)
$color4 = rgb(8E7D67)
$color5 = rgb(B7996F)
$color6 = rgb(B4A57E)
$color7 = rgb(EFE5CB)
$color8 = rgb(A7A08E)
$color9 = rgb(C0854D)
$color10 = rgb(C5874B)
$color11 = rgb(C59D6E)
$color12 = rgb(BEA789)
$color13 = rgb(F4CC93)
$color14 = rgb(F0DCA8)
$color15 = rgb(EFE5CB)
