# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(171717)
$foreground = rgb(DEDACF)
$color0 = rgb(000000)
$color1 = rgb(FF615A)
$color2 = rgb(B1E969)
$color3 = rgb(EBD99C)
$color4 = rgb(5DA9F6)
$color5 = rgb(E86AFF)
$color6 = rgb(82FFF7)
$color7 = rgb(DEDACF)
$color8 = rgb(313131)
$color9 = rgb(F58C80)
$color10 = rgb(DDF88F)
$color11 = rgb(EEE5B2)
$color12 = rgb(A5C7FF)
$color13 = rgb(DDAAFF)
$color14 = rgb(B7FFF9)
$color15 = rgb(FFFFFF)
